# Generated by Django 2.1.7 on 2019-05-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190520_0046'),
        ('operation', '0002_coursecomments_usercourse_userfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomments',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Video', verbose_name='章节'),
        ),
    ]
