# Generated by Django 2.1.7 on 2019-05-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_coursecomments_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='status',
        ),
    ]
