# Generated by Django 2.1.7 on 2019-05-25 22:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_usernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
