# Generated by Django 2.1.7 on 2019-05-26 01:08

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20190525_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='banner/2019/05'), verbose_name='轮播图'),
        ),
    ]
