# Generated by Django 2.1.7 on 2019-06-10 10:46

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20190526_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=stdimage.models.StdImageField(upload_to=stdimage.utils.UploadToUUID(path='banner/2019/06'), verbose_name='轮播图'),
        ),
    ]
