# Generated by Django 2.1.7 on 2019-05-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclassify',
            options={'verbose_name': '课程一级分类', 'verbose_name_plural': '课程一级分类'},
        ),
        migrations.AlterModelOptions(
            name='courseclassify2',
            options={'verbose_name': '课程二级分类', 'verbose_name_plural': '课程二级分类'},
        ),
    ]
