# Generated by Django 2.1.7 on 2019-05-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='课程详情'),
        ),
    ]
