# Generated by Django 2.1.7 on 2019-05-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.TextField(default='', verbose_name='老师告诉你'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_need_know',
            field=models.TextField(default='', verbose_name='课程须知'),
        ),
    ]
