# Generated by Django 2.1.7 on 2019-05-19 01:14

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190518_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=courses.models.upload_to_path, verbose_name='封面图'),
        ),
    ]
