# Generated by Django 2.1.7 on 2019-05-20 00:46

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190519_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='', max_length=200, upload_to=courses.models.upload_video_path, verbose_name='视频地址'),
        ),
    ]
