# Generated by Django 2.1.7 on 2019-05-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190520_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerCourse',
        ),
    ]
