# Generated by Django 2.1.7 on 2019-05-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_delete_bannercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassify2',
            name='parent_classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseClassify', verbose_name='一级分类'),
        ),
    ]
