# Generated by Django 2.1.7 on 2019-05-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_banner',
        ),
    ]
