# Generated by Django 2.1.7 on 2019-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursewiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclassify2',
            name='name',
            field=models.CharField(max_length=20, verbose_name='二级分类'),
        ),
    ]
