# Generated by Django 2.1.7 on 2019-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190517_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, choices=[('hd', '后端开发工程师'), ('qd', '前端开发工程师'), ('yd', '移动开发工程师'), ('test', '软件测试工程师'), ('linux', 'Linux系统工程师'), ('qz', '全栈开发工程师'), ('sf', '算法工程师'), ('student', '学生'), ('sa', '超级管理员'), ('admin', '管理员')], default='', max_length=10, verbose_name='职位'),
        ),
    ]
