# Generated by Django 2.1.7 on 2019-05-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190521_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default_s.png', upload_to='users/images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
