# Generated by Django 2.1.7 on 2019-05-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190519_0049'),
        ('users', '0006_auto_20190524_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '管理员'), (2, '教师'), (3, '普通用户')], default=3, verbose_name='用户类型'),
        ),
    ]
