# Generated by Django 2.1.7 on 2019-05-19 00:49

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='image/default_t.png', upload_to=teachers.models.upload_to_path, verbose_name='头像'),
        ),
    ]
