# Generated by Django 2.1.7 on 2019-05-27 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190519_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师信息', 'verbose_name_plural': '教师信息'},
        ),
    ]
