# Generated by Django 2.1.7 on 2019-05-25 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePost',
            new_name='Article',
        ),
    ]
